[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https://*.firebaseio.com https://*.googleapis.com https://*.gstatic.com https://*.google-analytics.com https://*.firebase.com https://*.firebaseapp.com https://*.googletagmanager.com https://*.asia-southeast1.firebasedatabase.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://*.google-analytics.com; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.google-analytics.com https://*.firebase.com https://*.firebaseapp.com https://*.asia-southeast1.firebasedatabase.app wss://*.firebaseio.com wss://*.asia-southeast1.firebasedatabase.app blob:; worker-src 'self' blob:; frame-src 'self' https://*.firebaseapp.com https://*.firebasedatabase.app https://*.asia-southeast1.firebasedatabase.app data:;"

# Additional headers for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
